// web/src/views/AccessView.tsx
import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react'

import client from '@/api/client'
import { apiErrorMessage } from '@/api/resources'
import { useAuthStore } from '@/stores/auth'

interface Permission { code: string; group: string; description: string }
interface Role { id: string; name: string; display_name: string; description: string; permissions: string[]; updated_at: string }
interface PermissionOverrides { allow: string[]; deny: string[] }
interface ManagedUser {
  id: string; username: string; nickname: string; is_superuser: boolean; is_active: boolean
  role_ids: string[]; permission_overrides: PermissionOverrides; effective_permissions: string[]; last_login_at?: string
}
interface AuditLog { id: string; action: string; resource_type: string; resource_id?: string; result: string; client_ip: string; created_at: string }

const emptyRole = { name: '', display_name: '', description: '', permissions: [] as string[] }
const emptyUser = { username: '', nickname: '', password: '', role_ids: [] as string[] }

export default function AccessView() {
  const current = useAuthStore((state) => state.user)
  const allowed = useCallback((permission: string) => Boolean(current?.is_superuser || current?.permissions.includes(permission)), [current])
  const canManageUsers = allowed('user.manage')
  const canManageRoles = allowed('role.manage')
  const canReadUsers = allowed('user.read') || canManageUsers
  const canReadRoles = allowed('role.read') || canManageRoles || canManageUsers
  const canReadAudit = allowed('audit.read')
  const tabs = useMemo(() => [
    ...(canReadUsers ? [{ id: 'users', label: '用户' }] : []),
    ...(canReadRoles ? [{ id: 'roles', label: '角色与功能' }] : []),
    ...(canReadAudit ? [{ id: 'audit', label: '审计日志' }] : []),
  ], [canReadAudit, canReadRoles, canReadUsers])
  const [active, setActive] = useState(tabs[0]?.id || '')
  const [users, setUsers] = useState<ManagedUser[]>([])
  const [roles, setRoles] = useState<Role[]>([])
  const [permissions, setPermissions] = useState<Permission[]>([])
  const [audits, setAudits] = useState<AuditLog[]>([])
  const [editingUser, setEditingUser] = useState<ManagedUser | null>(null)
  const [userRoles, setUserRoles] = useState<string[]>([])
  const [userOverrides, setUserOverrides] = useState<Record<string, 'inherit' | 'allow' | 'deny'>>({})
  const [roleForm, setRoleForm] = useState(emptyRole)
  const [editingRoleID, setEditingRoleID] = useState('')
  const [userForm, setUserForm] = useState(emptyUser)
  const [showRoleForm, setShowRoleForm] = useState(false)
  const [showUserForm, setShowUserForm] = useState(false)
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => { if (!tabs.some((tab) => tab.id === active)) setActive(tabs[0]?.id || '') }, [active, tabs])

  const refresh = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const [userResult, roleResult, permissionResult, auditResult] = await Promise.all([
        canReadUsers ? client.get<{ users: ManagedUser[] }>('/users?limit=200') : Promise.resolve(null),
        canReadRoles ? client.get<{ roles: Role[] }>('/roles') : Promise.resolve(null),
        canReadRoles ? client.get<{ permissions: Permission[] }>('/permissions') : Promise.resolve(null),
        canReadAudit ? client.get<{ audit_logs: AuditLog[] }>('/audit-logs?limit=100') : Promise.resolve(null),
      ])
      setUsers(userResult?.data.users || [])
      setRoles(roleResult?.data.roles || [])
      setPermissions(permissionResult?.data.permissions || [])
      setAudits(auditResult?.data.audit_logs || [])
    } catch (loadError) {
      setError(apiErrorMessage(loadError))
    } finally {
      setLoading(false)
    }
  }, [canReadAudit, canReadRoles, canReadUsers])

  useEffect(() => { void refresh() }, [refresh])

  const permissionGroups = useMemo(() => permissions.reduce<Record<string, Permission[]>>((groups, permission) => {
    if (!groups[permission.group]) groups[permission.group] = []
    groups[permission.group].push(permission)
    return groups
  }, {}), [permissions])

  function openUserEditor(user: ManagedUser) {
    const values: Record<string, 'inherit' | 'allow' | 'deny'> = {}
    permissions.forEach((permission) => { values[permission.code] = 'inherit' })
    user.permission_overrides.allow.forEach((permission) => { values[permission] = 'allow' })
    user.permission_overrides.deny.forEach((permission) => { values[permission] = 'deny' })
    setEditingUser(user)
    setUserRoles([...user.role_ids])
    setUserOverrides(values)
  }

  async function saveUserAccess() {
    if (!editingUser) return
    setSubmitting(true)
    setError('')
    try {
      const allow = Object.entries(userOverrides).filter(([, effect]) => effect === 'allow').map(([permission]) => permission)
      const deny = Object.entries(userOverrides).filter(([, effect]) => effect === 'deny').map(([permission]) => permission)
      await client.put(`/users/${editingUser.id}/roles`, { role_ids: userRoles })
      await client.put(`/users/${editingUser.id}/permissions`, { allow, deny })
      setEditingUser(null)
      await refresh()
    } catch (saveError) {
      setError(apiErrorMessage(saveError))
    } finally {
      setSubmitting(false)
    }
  }

  async function createUser(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setSubmitting(true)
    setError('')
    try {
      await client.post('/users', userForm)
      setUserForm(emptyUser)
      setShowUserForm(false)
      await refresh()
    } catch (createError) {
      setError(apiErrorMessage(createError))
    } finally {
      setSubmitting(false)
    }
  }

  async function toggleUser(user: ManagedUser) {
    setError('')
    try {
      await client.patch(`/users/${user.id}/status`, { active: !user.is_active })
      await refresh()
    } catch (toggleError) {
      setError(apiErrorMessage(toggleError))
    }
  }

  function editRole(role: Role) {
    setEditingRoleID(role.id)
    setRoleForm({ name: role.name, display_name: role.display_name, description: role.description || '', permissions: [...role.permissions] })
    setShowRoleForm(true)
  }

  async function saveRole(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setSubmitting(true)
    setError('')
    try {
      if (editingRoleID) await client.put(`/roles/${editingRoleID}`, roleForm)
      else await client.post('/roles', roleForm)
      setRoleForm(emptyRole)
      setEditingRoleID('')
      setShowRoleForm(false)
      await refresh()
    } catch (saveError) {
      setError(apiErrorMessage(saveError))
    } finally {
      setSubmitting(false)
    }
  }

  async function deleteRole(role: Role) {
    if (!window.confirm(`确认删除角色“${role.display_name}”？`)) return
    setError('')
    try {
      await client.delete(`/roles/${role.id}`)
      await refresh()
    } catch (deleteError) {
      setError(apiErrorMessage(deleteError))
    }
  }

  function toggleRolePermission(code: string) {
    setRoleForm((currentForm) => ({
      ...currentForm,
      permissions: currentForm.permissions.includes(code)
        ? currentForm.permissions.filter((item) => item !== code)
        : [...currentForm.permissions, code],
    }))
  }

  if (!tabs.length) return <section className="management-page"><div className="empty-state">当前账户没有身份与权限模块的查看权限</div></section>
  return <section className="access-page page-enter">
    <div className="page-heading modern-heading">
      <div><span className="section-label">完整 RBAC</span><h2>身份与权限</h2><p>角色定义通用功能权限，用户级允许或拒绝用于处理少量例外。</p></div>
      <div className="heading-actions"><button className="icon-button" type="button" onClick={() => void refresh()} disabled={loading}>↻</button>{active === 'users' && canManageUsers && <button className="primary-button" type="button" onClick={() => setShowUserForm(true)}>＋ 创建用户</button>}{active === 'roles' && canManageRoles && <button className="primary-button" type="button" onClick={() => { setEditingRoleID(''); setRoleForm(emptyRole); setShowRoleForm(true) }}>＋ 创建角色</button>}</div>
    </div>
    <div className="tab-bar">{tabs.map((tab) => <button type="button" className={active === tab.id ? 'active' : ''} key={tab.id} onClick={() => setActive(tab.id)}>{tab.label}</button>)}</div>
    {error && <div className="form-alert error system-alert" role="alert">{error}</div>}

    {active === 'users' && showUserForm && <form className="create-sheet" onSubmit={(event) => void createUser(event)}>
      <div className="sheet-header"><div><h3>创建用户</h3><p>创建后仍可单独调整角色和权限例外。</p></div><button type="button" onClick={() => setShowUserForm(false)}>×</button></div>
      <div className="form-grid"><label>用户名<input required maxLength={32} value={userForm.username} onChange={(event) => setUserForm({ ...userForm, username: event.target.value })} /></label><label>昵称<input maxLength={64} value={userForm.nickname} onChange={(event) => setUserForm({ ...userForm, nickname: event.target.value })} /></label><label className="span-2">初始密码<input required type="password" minLength={12} maxLength={128} value={userForm.password} onChange={(event) => setUserForm({ ...userForm, password: event.target.value })} /></label></div>
      <div className="role-choice-list">{roles.map((role) => <label key={role.id}><input type="checkbox" checked={userForm.role_ids.includes(role.id)} onChange={() => setUserForm((value) => ({ ...value, role_ids: value.role_ids.includes(role.id) ? value.role_ids.filter((id) => id !== role.id) : [...value.role_ids, role.id] }))} /><span><strong>{role.display_name}</strong><small>{role.description || role.name}</small></span></label>)}</div>
      <div className="form-actions"><button className="secondary-button" type="button" onClick={() => setShowUserForm(false)}>取消</button><button className="primary-button" disabled={submitting}>创建</button></div>
    </form>}

    {active === 'users' && <div className="access-user-list">{users.map((user) => <article className="access-user-card" key={user.id}>
      <div className="user-identity"><span>{(user.nickname || user.username).slice(0, 1)}</span><div><h3>{user.nickname || user.username}</h3><p>@{user.username}</p></div></div>
      <div className="user-role-summary">{user.is_superuser ? <b>超级管理员</b> : user.role_ids.map((roleID) => <span key={roleID}>{roles.find((role) => role.id === roleID)?.display_name || roleID}</span>)}{!user.is_superuser && user.role_ids.length === 0 && <span>未分配角色</span>}</div>
      <div className="user-permission-count"><strong>{user.is_superuser ? '全部' : user.effective_permissions.length}</strong><small>有效权限</small></div>
      <span className={`status-pill ${user.is_active ? 'status-succeeded' : 'status-canceled'}`}>{user.is_active ? '已启用' : '已停用'}</span>
      {canManageUsers && !user.is_superuser && <div className="card-actions"><button type="button" onClick={() => openUserEditor(user)}>配置权限</button><button type="button" onClick={() => void toggleUser(user)}>{user.is_active ? '停用' : '启用'}</button></div>}
    </article>)}</div>}

    {editingUser && <div className="access-editor-backdrop"><section className="access-editor">
      <div className="sheet-header"><div><h3>配置 {editingUser.nickname || editingUser.username}</h3><p>拒绝优先于允许；“继承角色”不会创建用户级规则。</p></div><button type="button" onClick={() => setEditingUser(null)}>×</button></div>
      <h4>角色</h4><div className="role-choice-list">{roles.map((role) => <label key={role.id}><input type="checkbox" checked={userRoles.includes(role.id)} onChange={() => setUserRoles((values) => values.includes(role.id) ? values.filter((id) => id !== role.id) : [...values, role.id])} /><span><strong>{role.display_name}</strong><small>{role.description || role.name}</small></span></label>)}</div>
      <h4>用户权限例外</h4><div className="permission-groups">{Object.entries(permissionGroups).map(([group, items]) => <fieldset key={group}><legend>{group}</legend>{items.map((permission) => <label key={permission.code}><span><strong>{permission.description}</strong><code>{permission.code}</code></span><select value={userOverrides[permission.code] || 'inherit'} onChange={(event) => setUserOverrides((values) => ({ ...values, [permission.code]: event.target.value as 'inherit' | 'allow' | 'deny' }))}><option value="inherit">继承角色</option><option value="allow">额外允许</option><option value="deny">显式拒绝</option></select></label>)}</fieldset>)}</div>
      <div className="form-actions"><button className="secondary-button" type="button" onClick={() => setEditingUser(null)}>取消</button><button className="primary-button" type="button" disabled={submitting} onClick={() => void saveUserAccess()}>保存权限</button></div>
    </section></div>}

    {active === 'roles' && showRoleForm && <form className="create-sheet role-editor-sheet" onSubmit={(event) => void saveRole(event)}>
      <div className="sheet-header"><div><h3>{editingRoleID ? '修改角色' : '创建角色'}</h3><p>按功能勾选最小权限，菜单与接口会使用同一份有效权限。</p></div><button type="button" onClick={() => setShowRoleForm(false)}>×</button></div>
      <div className="form-grid"><label>角色标识<input required value={roleForm.name} onChange={(event) => setRoleForm({ ...roleForm, name: event.target.value })} placeholder="release_operator" /></label><label>显示名称<input required value={roleForm.display_name} onChange={(event) => setRoleForm({ ...roleForm, display_name: event.target.value })} /></label><label className="span-2">说明<input value={roleForm.description} onChange={(event) => setRoleForm({ ...roleForm, description: event.target.value })} /></label></div>
      <div className="permission-groups role-permission-groups">{Object.entries(permissionGroups).map(([group, items]) => <fieldset key={group}><legend>{group}</legend>{items.map((permission) => <label key={permission.code}><input type="checkbox" checked={roleForm.permissions.includes(permission.code)} onChange={() => toggleRolePermission(permission.code)} /><span><strong>{permission.description}</strong><code>{permission.code}</code></span></label>)}</fieldset>)}</div>
      <div className="form-actions"><button className="secondary-button" type="button" onClick={() => setShowRoleForm(false)}>取消</button><button className="primary-button" disabled={submitting}>保存角色</button></div>
    </form>}

    {active === 'roles' && <div className="role-card-grid">{roles.map((role) => <article className="role-card" key={role.id}><div><span className="role-mark">R</span><h3>{role.display_name}</h3><code>{role.name}</code></div><p>{role.description || '未填写角色说明'}</p><div className="role-permission-tags">{role.permissions.slice(0, 8).map((permission) => <span key={permission}>{permission}</span>)}{role.permissions.length > 8 && <span>+{role.permissions.length - 8}</span>}</div>{canManageRoles && <div className="card-actions"><button type="button" onClick={() => editRole(role)}>编辑</button><button className="danger-action" type="button" onClick={() => void deleteRole(role)}>删除</button></div>}</article>)}</div>}

    {active === 'audit' && <div className="audit-table"><table><thead><tr><th>时间</th><th>动作</th><th>资源</th><th>结果</th><th>来源 IP</th></tr></thead><tbody>{audits.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString('zh-CN', { hour12: false })}</td><td><code>{item.action}</code></td><td>{item.resource_type}{item.resource_id ? ` / ${item.resource_id}` : ''}</td><td>{item.result}</td><td>{item.client_ip}</td></tr>)}</tbody></table></div>}
  </section>
}

// web/src/views/AccessView.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Modal, message } from 'ant-design-vue'
import { Plus, RefreshCw } from 'lucide-vue-next'

import client from '@/api/client'
import { apiErrorMessage, type ResourceRecord } from '@/api/resources'
import PageToolbar from '@/components/PageToolbar.vue'
import ResourceTable from '@/components/ResourceTable.vue'
import { useAuthStore } from '@/stores/auth'

interface Permission { code:string;group:string;description:string }
interface Role extends ResourceRecord { id:string;name:string;display_name:string;description:string;permissions:string[];updated_at:string }
interface ManagedUser extends ResourceRecord { id:string;username:string;nickname:string;is_superuser:boolean;is_active:boolean;role_ids:string[];permission_overrides:{allow:string[];deny:string[]};effective_permissions:string[];last_login_at?:string }
interface AuditLog extends ResourceRecord { id:string;action:string;resource_type:string;resource_id?:string;result:string;client_ip:string;created_at:string }

const route=useRoute(),router=useRouter(),auth=useAuthStore()
const users=ref<ManagedUser[]>([]),roles=ref<Role[]>([]),permissions=ref<Permission[]>([]),audits=ref<AuditLog[]>([]),loading=ref(false),saving=ref(false)
const userFormOpen=ref(false),roleFormOpen=ref(false),accessOpen=ref(false),editingRoleID=ref(''),editingUser=ref<ManagedUser|null>(null)
const userForm=reactive({username:'',nickname:'',password:'',role_ids:[] as string[]})
const roleForm=reactive({name:'',display_name:'',description:'',permissions:[] as string[]})
const accessForm=reactive({role_ids:[] as string[],effects:{} as Record<string,'inherit'|'allow'|'deny'>})

const tabs=computed(()=>[
  ...(auth.canAny(['user.read','user.manage'])?[{key:'users',label:'用户管理'}]:[]),
  ...(auth.canAny(['role.read','role.manage','user.manage'])?[{key:'roles',label:'角色与功能'}]:[]),
  ...(auth.canAny(['audit.read'])?[{key:'audit',label:'审计日志'}]:[]),
])
const active=computed(()=>tabs.value.some(item=>item.key===route.query.view)?String(route.query.view):tabs.value[0]?.key||'')
const permissionGroups=computed(()=>permissions.value.reduce<Record<string,Permission[]>>((result,item)=>{(result[item.group]??=[]).push(item);return result},{}))
const userColumns=[{key:'username',label:'用户名'},{key:'nickname',label:'昵称'},{key:'role_ids',label:'角色'},{key:'effective_permissions',label:'有效权限'},{key:'is_active',label:'状态'},{key:'last_login_at',label:'最后登录'}]
const roleColumns=[{key:'display_name',label:'名称'},{key:'name',label:'标识'},{key:'description',label:'说明'},{key:'permissions',label:'权限数量'},{key:'updated_at',label:'更新时间'}]
const auditColumns=[{key:'action',label:'动作'},{key:'resource_type',label:'资源'},{key:'resource_id',label:'资源 ID'},{key:'result',label:'结果'},{key:'client_ip',label:'来源 IP'},{key:'created_at',label:'时间'}]

async function refresh(){loading.value=true;try{const [u,r,p,a]=await Promise.all([auth.canAny(['user.read','user.manage'])?client.get<{users:ManagedUser[]}>('/users?limit=200'):null,auth.canAny(['role.read','role.manage','user.manage'])?client.get<{roles:Role[]}>('/roles'):null,auth.canAny(['role.read','role.manage','user.manage'])?client.get<{permissions:Permission[]}>('/permissions'):null,auth.canAny(['audit.read'])?client.get<{audit_logs:AuditLog[]}>('/audit-logs?limit=100'):null]);users.value=u?.data.users||[];roles.value=r?.data.roles||[];permissions.value=p?.data.permissions||[];audits.value=a?.data.audit_logs||[]}catch(error){message.error(apiErrorMessage(error))}finally{loading.value=false}}
function selectTab(key:string){void router.replace({query:{...route.query,view:key}})}
function resetUser(){Object.assign(userForm,{username:'',nickname:'',password:'',role_ids:[]})}
function resetRole(){Object.assign(roleForm,{name:'',display_name:'',description:'',permissions:[]});editingRoleID.value=''}
async function createUser(){saving.value=true;try{await client.post('/users',userForm);message.success('用户已创建');userFormOpen.value=false;resetUser();await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
function editRole(item:Role){Object.assign(roleForm,{name:item.name,display_name:item.display_name,description:item.description||'',permissions:[...item.permissions]});editingRoleID.value=item.id;roleFormOpen.value=true}
async function saveRole(){saving.value=true;try{if(editingRoleID.value)await client.put(`/roles/${editingRoleID.value}`,roleForm);else await client.post('/roles',roleForm);message.success('角色已保存');roleFormOpen.value=false;resetRole();await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
function removeRole(item:Role){Modal.confirm({title:`删除角色“${item.display_name}”？`,okType:'danger',async onOk(){try{await client.delete(`/roles/${item.id}`);await refresh()}catch(error){message.error(apiErrorMessage(error))}}})}
async function toggleUser(item:ManagedUser){try{await client.patch(`/users/${item.id}/status`,{active:!item.is_active});await refresh()}catch(error){message.error(apiErrorMessage(error))}}
function editAccess(item:ManagedUser){editingUser.value=item;accessForm.role_ids=[...item.role_ids];accessForm.effects={};permissions.value.forEach(p=>accessForm.effects[p.code]='inherit');item.permission_overrides.allow.forEach(p=>accessForm.effects[p]='allow');item.permission_overrides.deny.forEach(p=>accessForm.effects[p]='deny');accessOpen.value=true}
async function saveAccess(){if(!editingUser.value)return;saving.value=true;try{const allow=Object.entries(accessForm.effects).filter(([,v])=>v==='allow').map(([k])=>k),deny=Object.entries(accessForm.effects).filter(([,v])=>v==='deny').map(([k])=>k);await client.put(`/users/${editingUser.value.id}/roles`,{role_ids:accessForm.role_ids});await client.put(`/users/${editingUser.value.id}/permissions`,{allow,deny});message.success('用户权限已更新');accessOpen.value=false;await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}

watch(active,(value)=>{if(value&&route.query.view!==value)selectTab(value)},{immediate:true})
onMounted(refresh)
</script>

<template>
  <section>
    <PageToolbar :description="active==='audit'?'查看身份、资源、操作结果和请求来源，不展示任何密钥内容。':active==='roles'?'用角色组合可复用的功能权限。':'维护账户状态、角色归属与用户级允许或拒绝例外。'"><a-button :loading="loading" @click="refresh"><RefreshCw :size="15"/>刷新</a-button><a-button v-if="active==='users'&&auth.canAny(['user.manage'])" type="primary" @click="resetUser();userFormOpen=true"><Plus :size="15"/>创建用户</a-button><a-button v-if="active==='roles'&&auth.canAny(['role.manage'])" type="primary" @click="resetRole();roleFormOpen=true"><Plus :size="15"/>创建角色</a-button></PageToolbar>
    <a-segmented :value="active" :options="tabs.map(item=>({value:item.key,label:item.label}))" class="access-tabs" @change="(value:string)=>selectTab(value)" />
    <div class="vben-card">
      <ResourceTable v-if="active==='users'" :rows="users" :columns="userColumns" :loading="loading"><template #cell-role_ids="{row}"><div class="tag-list"><a-tag v-if="row.is_superuser" color="purple">超级管理员</a-tag><a-tag v-for="id in row.role_ids" :key="String(id)">{{ roles.find(role=>role.id===id)?.display_name||id }}</a-tag></div></template><template #cell-effective_permissions="{value}">{{ Array.isArray(value)?value.length:'全部' }}</template><template #actions="{row}"><template v-if="auth.canAny(['user.manage'])&&!row.is_superuser"><a-button type="link" @click="editAccess(row as ManagedUser)">配置权限</a-button><a-button type="link" :danger="row.is_active" @click="toggleUser(row as ManagedUser)">{{ row.is_active?'停用':'启用' }}</a-button></template></template></ResourceTable>
      <ResourceTable v-else-if="active==='roles'" :rows="roles" :columns="roleColumns" :loading="loading"><template #cell-permissions="{value}">{{ Array.isArray(value)?value.length:0 }} 项</template><template v-if="auth.canAny(['role.manage'])" #actions="{row}"><a-button type="link" @click="editRole(row as Role)">编辑</a-button><a-button type="link" danger @click="removeRole(row as Role)">删除</a-button></template></ResourceTable>
      <ResourceTable v-else :rows="audits" :columns="auditColumns" :loading="loading"><template #cell-result="{value}"><a-tag :color="value==='success'?'success':'error'">{{ value }}</a-tag></template></ResourceTable>
    </div>

    <a-modal v-model:open="userFormOpen" title="创建用户" :confirm-loading="saving" ok-text="创建" @ok="createUser"><a-form layout="vertical"><a-form-item label="用户名" required><a-input v-model:value="userForm.username" maxlength="32"/></a-form-item><a-form-item label="昵称"><a-input v-model:value="userForm.nickname" maxlength="64"/></a-form-item><a-form-item label="初始密码" required><a-input-password v-model:value="userForm.password" minlength="12" maxlength="128"/></a-form-item><a-form-item label="角色"><a-select v-model:value="userForm.role_ids" mode="multiple" :options="roles.map(role=>({value:role.id,label:role.display_name}))"/></a-form-item></a-form></a-modal>
    <a-drawer v-model:open="roleFormOpen" :title="editingRoleID?'编辑角色':'创建角色'" width="620"><a-form layout="vertical"><a-form-item label="标识" required><a-input v-model:value="roleForm.name" :disabled="Boolean(editingRoleID)"/></a-form-item><a-form-item label="名称" required><a-input v-model:value="roleForm.display_name"/></a-form-item><a-form-item label="说明"><a-textarea v-model:value="roleForm.description" :rows="3"/></a-form-item><div v-for="(items,group) in permissionGroups" :key="group" class="permission-group"><strong>{{ group }}</strong><a-checkbox-group v-model:value="roleForm.permissions"><div class="permission-options"><a-checkbox v-for="item in items" :key="item.code" :value="item.code"><span>{{ item.code }}</span><small>{{ item.description }}</small></a-checkbox></div></a-checkbox-group></div><a-button type="primary" block :loading="saving" @click="saveRole">保存</a-button></a-form></a-drawer>
    <a-drawer v-model:open="accessOpen" :title="`配置 ${editingUser?.nickname||editingUser?.username||''}`" width="760"><a-alert type="info" show-icon message="用户级拒绝优先于角色允许；“继承角色”不会创建用户规则。"/><h3>角色</h3><a-checkbox-group v-model:value="accessForm.role_ids" :options="roles.map(role=>({value:role.id,label:role.display_name}))"/><h3>用户权限例外</h3><div v-for="(items,group) in permissionGroups" :key="group" class="override-group"><strong>{{ group }}</strong><div v-for="item in items" :key="item.code" class="override-row"><span><b>{{ item.code }}</b><small>{{ item.description }}</small></span><a-segmented v-model:value="accessForm.effects[item.code]" :options="[{label:'继承',value:'inherit'},{label:'允许',value:'allow'},{label:'拒绝',value:'deny'}]"/></div></div><a-button type="primary" block :loading="saving" @click="saveAccess">保存权限</a-button></a-drawer>
  </section>
</template>

<style scoped>.access-tabs{margin-bottom:12px}.tag-list{display:flex;flex-wrap:wrap;gap:3px}.permission-group,.override-group{margin:16px 0;padding:14px;border:1px solid var(--zrt-border);border-radius:7px}.permission-options{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:12px}.permission-options :deep(.ant-checkbox-wrapper){align-items:flex-start}.permission-options span,.permission-options small,.override-row span b,.override-row span small{display:block}.permission-options small,.override-row small{color:var(--zrt-muted);font-size:11px}.override-row{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:10px 0;border-top:1px solid var(--zrt-border)}h3{margin:24px 0 12px}@media(max-width:650px){.permission-options{grid-template-columns:1fr}.override-row{align-items:flex-start;flex-direction:column}}
</style>
