// web/src/views/CredentialView.tsx
import { type FormEvent, useCallback, useEffect, useState } from 'react'

import client from '@/api/client'
import { apiErrorMessage } from '@/api/resources'
import { useAuthStore } from '@/stores/auth'

interface GitCredential {
  id: string
  name: string
  provider: string
  auth_type: 'token' | 'ssh_key'
  username?: string
  secret_hint: string
  created_at: string
  updated_at: string
}

const emptyForm = { name: '', provider: 'github', auth_type: 'token' as 'token' | 'ssh_key', username: '', secret: '' }

function providerLabel(provider: string) {
  return ({ github: 'GitHub', gitlab: 'GitLab', gitea: 'Gitea', gitee: 'Gitee', generic: '普通 Git' } as Record<string, string>)[provider] || provider
}

export default function CredentialView() {
  const user = useAuthStore((state) => state.user)
  const canManage = Boolean(user?.is_superuser || user?.permissions.includes('credential.manage'))
  const [items, setItems] = useState<GitCredential[]>([])
  const [form, setForm] = useState(emptyForm)
  const [editingID, setEditingID] = useState('')
  const [formOpen, setFormOpen] = useState(false)
  const [revealed, setRevealed] = useState<Record<string, string>>({})
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  const refresh = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const response = await client.get<{ credentials: GitCredential[] }>('/git-credentials')
      setItems(response.data.credentials)
    } catch (loadError) {
      setError(apiErrorMessage(loadError))
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { void refresh() }, [refresh])

  function closeForm() {
    setFormOpen(false)
    setEditingID('')
    setForm(emptyForm)
  }

  function edit(item: GitCredential) {
    setEditingID(item.id)
    setForm({ name: item.name, provider: item.provider, auth_type: item.auth_type, username: item.username || '', secret: '' })
    setFormOpen(true)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setSubmitting(true)
    setError('')
    try {
      const payload = { ...form, secret: form.secret || null }
      if (editingID) await client.put(`/git-credentials/${editingID}`, payload)
      else await client.post('/git-credentials', payload)
      closeForm()
      await refresh()
    } catch (submitError) {
      setError(apiErrorMessage(submitError))
    } finally {
      setSubmitting(false)
    }
  }

  async function reveal(item: GitCredential) {
    if (revealed[item.id]) {
      setRevealed((current) => { const next = { ...current }; delete next[item.id]; return next })
      return
    }
    setError('')
    try {
      const response = await client.get<{ secret: string }>(`/git-credentials/${item.id}/secret`)
      setRevealed((current) => ({ ...current, [item.id]: response.data.secret }))
    } catch (revealError) {
      setError(apiErrorMessage(revealError))
    }
  }

  async function remove(item: GitCredential) {
    if (!window.confirm(`确认删除令牌“${item.name}”？`)) return
    setError('')
    try {
      await client.delete(`/git-credentials/${item.id}`)
      await refresh()
    } catch (deleteError) {
      setError(apiErrorMessage(deleteError))
    }
  }

  return <section className="credential-page page-enter">
    <div className="page-heading modern-heading">
      <div><span className="section-label">个人安全空间</span><h2>我的 Git 令牌</h2><p>每个账户只能查看和管理自己保存的令牌，仓库只保存引用关系。</p></div>
      <div className="heading-actions"><button className="icon-button" type="button" onClick={() => void refresh()} disabled={loading}>↻</button>{canManage && <button className="primary-button" type="button" onClick={() => setFormOpen((value) => !value)}>＋ 保存令牌</button>}</div>
    </div>
    {error && <div className="form-alert error system-alert" role="alert">{error}</div>}
    {formOpen && <form className="create-sheet credential-sheet" onSubmit={(event) => void submit(event)}>
      <div className="sheet-header"><div><h3>{editingID ? '修改 Git 令牌' : '保存 Git 令牌'}</h3><p>令牌使用 ZRT 主密钥加密，只有当前用户可以通过界面读取。</p></div><button type="button" onClick={closeForm}>×</button></div>
      <div className="form-grid">
        <label>名称<input required maxLength={128} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="例如：GitHub 生产账号" /></label>
        <label>平台<select value={form.provider} onChange={(event) => setForm({ ...form, provider: event.target.value })}><option value="github">GitHub</option><option value="gitlab">GitLab</option><option value="gitea">Gitea</option><option value="gitee">Gitee</option><option value="generic">普通 Git</option></select></label>
        <label>类型<select value={form.auth_type} onChange={(event) => setForm({ ...form, auth_type: event.target.value as 'token' | 'ssh_key' })}><option value="token">访问令牌</option><option value="ssh_key">SSH 私钥</option></select></label>
        <label>用户名<input maxLength={255} value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} placeholder="部分平台可留空" /></label>
        <label className="span-2">{form.auth_type === 'token' ? '令牌' : 'SSH 私钥'}<textarea required={!editingID} rows={form.auth_type === 'ssh_key' ? 8 : 3} value={form.secret} onChange={(event) => setForm({ ...form, secret: event.target.value })} placeholder={editingID ? '留空表示保持原值' : '请输入凭据内容'} /></label>
      </div>
      <div className="form-actions"><button className="secondary-button" type="button" onClick={closeForm}>取消</button><button className="primary-button" type="submit" disabled={submitting}>{submitting ? '保存中…' : '保存'}</button></div>
    </form>}
    <div className="credential-grid">{items.map((item) => <article className="credential-card" key={item.id}>
      <div className="credential-card-head"><span className="credential-provider">{providerLabel(item.provider).slice(0, 2)}</span><div><h3>{item.name}</h3><p>{providerLabel(item.provider)} · {item.auth_type === 'token' ? '访问令牌' : 'SSH 私钥'}</p></div></div>
      <div className="credential-secret"><code>{revealed[item.id] || item.secret_hint}</code><button type="button" onClick={() => void reveal(item)}>{revealed[item.id] ? '隐藏' : '查看'}</button></div>
      <div className="meta-row"><span>{item.username || '未设置用户名'}</span><span>{new Date(item.updated_at).toLocaleString('zh-CN', { hour12: false })}</span></div>
      {canManage && <div className="card-actions"><button type="button" onClick={() => edit(item)}>编辑</button><button className="danger-action" type="button" onClick={() => void remove(item)}>删除</button></div>}
    </article>)}{!loading && items.length === 0 && <div className="empty-state modern-empty"><span className="empty-icon">⌁</span><h3>还没有保存令牌</h3><p>保存后可以在创建代码仓库时直接选择。</p></div>}</div>
  </section>
}

// web/src/views/CredentialView.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Modal, message } from 'ant-design-vue'
import { Eye, EyeOff, KeyRound, Plus, RefreshCw } from 'lucide-vue-next'

import client from '@/api/client'
import { apiErrorMessage, type ResourceRecord } from '@/api/resources'
import PageToolbar from '@/components/PageToolbar.vue'
import ResourceTable from '@/components/ResourceTable.vue'
import { useAuthStore } from '@/stores/auth'

interface GitCredential extends ResourceRecord { id: string; name: string; provider: string; auth_type: 'token'|'ssh_key'; username?: string; secret_hint: string; updated_at: string }
const auth = useAuthStore()
const items = ref<GitCredential[]>([])
const loading = ref(false)
const submitting = ref(false)
const formOpen = ref(false)
const editingID = ref('')
const revealed = reactive<Record<string,string>>({})
const form = reactive({ name: '', provider: 'github', auth_type: 'token' as 'token'|'ssh_key', username: '', secret: '' })
const columns = [{ key:'name',label:'名称'},{key:'provider',label:'平台'},{key:'auth_type',label:'类型'},{key:'username',label:'用户名'},{key:'secret_hint',label:'凭据'},{key:'updated_at',label:'更新时间'}]
const providerNames: Record<string,string> = { github:'GitHub',gitlab:'GitLab',gitea:'Gitea',gitee:'Gitee',generic:'普通 Git' }

function reset() { Object.assign(form,{name:'',provider:'github',auth_type:'token',username:'',secret:''}); editingID.value=''; formOpen.value=false }
async function refresh() { loading.value=true; try { items.value=(await client.get<{credentials:GitCredential[]}>('/git-credentials')).data.credentials } catch(error){message.error(apiErrorMessage(error))} finally{loading.value=false} }
function edit(item:GitCredential){ Object.assign(form,{name:item.name,provider:item.provider,auth_type:item.auth_type,username:item.username||'',secret:''});editingID.value=item.id;formOpen.value=true }
async function submit(){submitting.value=true;try{const payload={...form,secret:form.secret||null};if(editingID.value)await client.put(`/git-credentials/${editingID.value}`,payload);else await client.post('/git-credentials',payload);message.success('Git 凭据已保存');reset();await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{submitting.value=false}}
async function reveal(item:GitCredential){if(revealed[item.id]){delete revealed[item.id];return}try{revealed[item.id]=(await client.get<{secret:string}>(`/git-credentials/${item.id}/secret`)).data.secret}catch(error){message.error(apiErrorMessage(error))}}
function remove(item:GitCredential){Modal.confirm({title:`删除“${item.name}”？`,content:'使用此凭据的仓库可能无法继续访问。',okType:'danger',okText:'删除',cancelText:'取消',async onOk(){try{await client.delete(`/git-credentials/${item.id}`);message.success('凭据已删除');await refresh()}catch(error){message.error(apiErrorMessage(error))}}})}
onMounted(refresh)
</script>

<template>
  <section>
    <PageToolbar description="每个账户只能查看和管理自己保存的令牌，仓库只保存引用关系。"><a-button :loading="loading" @click="refresh"><RefreshCw :size="15" />刷新</a-button><a-button v-if="auth.canAny(['credential.manage'])" type="primary" @click="reset();formOpen=true"><Plus :size="15" />保存令牌</a-button></PageToolbar>
    <div class="vben-card"><ResourceTable :rows="items" :columns="columns" :loading="loading">
      <template #cell-provider="{ value }"><a-tag color="blue">{{ providerNames[String(value)] || value }}</a-tag></template>
      <template #cell-auth_type="{ value }">{{ value === 'ssh_key' ? 'SSH 私钥' : '访问令牌' }}</template>
      <template #cell-secret_hint="{ row }"><span class="secret-cell"><code>{{ revealed[String(row.id)] || row.secret_hint }}</code><a-button type="text" size="small" @click="reveal(row as GitCredential)"><EyeOff v-if="revealed[String(row.id)]" :size="15"/><Eye v-else :size="15"/></a-button></span></template>
      <template v-if="auth.canAny(['credential.manage'])" #actions="{ row }"><a-button type="link" @click="edit(row as GitCredential)">编辑</a-button><a-button type="link" danger @click="remove(row as GitCredential)">删除</a-button></template>
    </ResourceTable></div>

    <a-drawer v-model:open="formOpen" :title="editingID ? '修改 Git 凭据' : '保存 Git 凭据'" width="520" @close="reset">
      <a-alert type="info" show-icon message="凭据使用 ZRT 主密钥加密，且只对当前用户可见。" class="form-alert" />
      <a-form layout="vertical" @finish="submit">
        <a-form-item label="名称" required><a-input v-model:value="form.name" maxlength="128" placeholder="例如：GitHub 生产账号" /></a-form-item>
        <div class="form-row"><a-form-item label="平台" required><a-select v-model:value="form.provider" :options="Object.entries(providerNames).map(([value,label])=>({value,label}))" /></a-form-item><a-form-item label="类型" required><a-select v-model:value="form.auth_type" :options="[{value:'token',label:'访问令牌'},{value:'ssh_key',label:'SSH 私钥'}]" /></a-form-item></div>
        <a-form-item label="用户名"><a-input v-model:value="form.username" maxlength="255" placeholder="部分平台可留空" /></a-form-item>
        <a-form-item :label="form.auth_type === 'token' ? '令牌' : 'SSH 私钥'" :required="!editingID"><a-textarea v-model:value="form.secret" :rows="form.auth_type === 'ssh_key' ? 8 : 3" :placeholder="editingID ? '留空表示保持原值' : '请输入凭据内容'" /></a-form-item>
        <a-button type="primary" html-type="submit" block :loading="submitting"><KeyRound :size="15" />保存</a-button>
      </a-form>
    </a-drawer>
  </section>
</template>

<style scoped>.secret-cell{display:flex;max-width:280px;align-items:center;gap:6px}.secret-cell code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.form-alert{margin-bottom:18px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}</style>
