// web/src/views/LoginView.vue
<script setup lang="ts">
import axios from 'axios'
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Languages, LockKeyhole, Moon, Sun, UserRound } from 'lucide-vue-next'

import { getLoginProviders, type LoginProvider } from '@/api/client'
import { useAuthStore } from '@/stores/auth'
import { usePreferencesStore } from '@/stores/preferences'

const route = useRoute()
const router = useRouter()
const auth = useAuthStore()
const preferences = usePreferencesStore()
const username = ref('')
const password = ref('')
const provider = ref('local')
const providers = ref<LoginProvider[]>([])
const loading = ref(false)
const error = ref('')

const ldapProviders = computed(() => providers.value.filter((item) => item.type === 'ldap'))
const oauthProviders = computed(() => providers.value.filter((item) => item.type !== 'ldap'))

function safeRedirect(value: unknown) {
  return typeof value === 'string' && value.startsWith('/') && !value.startsWith('//') && !value.includes('\\') ? value : '/'
}

async function submit() {
  if (!username.value.trim() || !password.value) {
    error.value = '请输入用户名和密码。'
    return
  }
  loading.value = true
  error.value = ''
  try {
    if (provider.value === 'local') await auth.login(username.value, password.value)
    else await auth.loginLDAP(provider.value, username.value, password.value)
    await router.replace(safeRedirect(route.query.redirect))
  } catch (submitError) {
    error.value = axios.isAxiosError(submitError)
      ? (submitError.response?.data as { message?: string } | undefined)?.message || '登录服务暂时不可用，请稍后重试。'
      : '登录服务暂时不可用，请稍后重试。'
  } finally {
    loading.value = false
  }
}

function externalLogin(item: LoginProvider) {
  const returnTo = safeRedirect(route.query.redirect)
  window.location.assign(`/api/v1/auth/oauth/${encodeURIComponent(item.id)}/start?return_to=${encodeURIComponent(returnTo)}`)
}

onMounted(async () => {
  try { providers.value = await getLoginProviders() } catch { providers.value = [] }
  if (route.query.reason === 'unavailable') error.value = '暂时无法读取登录状态，请确认 ZRT 服务已启动。'
})
</script>

<template>
  <main class="vben-login-page">
    <div class="login-tools">
      <a-dropdown><button type="button"><Languages /></button><template #overlay><a-menu @click="({ key }: { key: string }) => preferences.setLocale(key as 'zh-CN' | 'en-US')"><a-menu-item key="zh-CN">简体中文</a-menu-item><a-menu-item key="en-US">English</a-menu-item></a-menu></template></a-dropdown>
      <button type="button" @click="preferences.toggleTheme()"><Sun v-if="preferences.theme === 'dark'" /><Moon v-else /></button>
    </div>
    <section class="login-visual">
      <div class="visual-brand"><span class="logo-mark"><span>Z</span></span><strong>ZRT</strong></div>
      <div class="visual-copy"><p>持续交付与运行管理平台</p><h1>让每一次变更<br>都有清晰路径。</h1><span>从代码检查、镜像构建到环境发布，把复杂流程收进一个可靠的工作台。</span></div>
      <div class="visual-orbits"><i /><i /><i /></div>
    </section>
    <section class="login-panel">
      <form class="login-card" @submit.prevent="submit">
        <div class="login-card-head"><h2>欢迎回来</h2><p>登录 ZRT 继续工作</p></div>
        <a-alert v-if="error" type="error" show-icon :message="error" />
        <a-segmented v-if="ldapProviders.length" v-model:value="provider" block :options="[{ label: 'ZRT 账号', value: 'local' }, ...ldapProviders.map((item) => ({ label: item.display_name, value: item.id }))]" />
        <label><span>用户名</span><a-input v-model:value="username" size="large" autocomplete="username" placeholder="请输入用户名"><template #prefix><UserRound /></template></a-input></label>
        <label><span>密码</span><a-input-password v-model:value="password" size="large" autocomplete="current-password" placeholder="请输入密码"><template #prefix><LockKeyhole /></template></a-input-password></label>
        <a-button type="primary" html-type="submit" size="large" block :loading="loading">登录</a-button>
        <template v-if="oauthProviders.length"><a-divider>其他登录方式</a-divider><div class="oauth-list"><a-button v-for="item in oauthProviders" :key="item.id" @click="externalLogin(item)">{{ item.display_name }}</a-button></div></template>
      </form>
      <p class="login-copyright">ZRT · 安全、清晰、可追踪</p>
    </section>
  </main>
</template>

<style scoped>
.vben-login-page { position: relative; display: grid; min-height: 100vh; grid-template-columns: minmax(380px,1.08fr) minmax(420px,.92fr); overflow: hidden; background: var(--zrt-surface); }
.login-tools { position: absolute; top: 20px; right: 22px; z-index: 3; display: flex; gap: 5px; }
.login-tools button { display: grid; width: 34px; height: 34px; place-items: center; border: 0; border-radius: 6px; color: var(--zrt-muted); background: transparent; cursor: pointer; }
.login-tools button:hover { color: var(--zrt-primary); background: var(--zrt-surface-soft); }
.login-tools svg { width: 18px; }
.login-visual { position: relative; display: flex; min-height: 100vh; flex-direction: column; justify-content: space-between; overflow: hidden; padding: 42px 7vw 64px; color: #fff; background: radial-gradient(circle at 18% 20%,rgb(116 107 255 / 95%),transparent 38%),radial-gradient(circle at 78% 78%,rgb(47 201 190 / 80%),transparent 36%),linear-gradient(145deg,#2d3c86,#5367df 56%,#335e8c); }
.login-visual::after { position: absolute; inset: 0; background-image: linear-gradient(rgb(255 255 255 / 5%) 1px,transparent 1px),linear-gradient(90deg,rgb(255 255 255 / 5%) 1px,transparent 1px); background-size: 42px 42px; content: ""; mask-image: linear-gradient(to bottom,black,transparent); }
.visual-brand, .visual-copy { position: relative; z-index: 1; }
.visual-brand { display: flex; align-items: center; gap: 13px; font-size: 21px; letter-spacing: .06em; }
.visual-copy { max-width: 590px; }
.visual-copy p { margin: 0 0 16px; color: rgb(255 255 255 / 72%); letter-spacing: .08em; }
.visual-copy h1 { margin: 0 0 22px; font-size: clamp(42px,4.2vw,68px); line-height: 1.12; letter-spacing: -.04em; }
.visual-copy > span { display: block; max-width: 500px; color: rgb(255 255 255 / 74%); font-size: 16px; line-height: 1.8; }
.visual-orbits { position: absolute; right: -150px; bottom: -170px; width: 520px; height: 520px; border: 1px solid rgb(255 255 255 / 15%); border-radius: 50%; }
.visual-orbits i { position: absolute; inset: 65px; border: 1px solid rgb(255 255 255 / 12%); border-radius: 50%; }
.visual-orbits i:nth-child(2) { inset: 135px; }.visual-orbits i:nth-child(3) { inset: 205px; background: rgb(255 255 255 / 9%); }
.login-panel { display: flex; min-height: 100vh; align-items: center; justify-content: center; flex-direction: column; padding: 80px 34px 34px; background: var(--zrt-surface); }
.login-card { display: grid; width: min(390px,100%); gap: 20px; }
.login-card-head h2 { margin: 0; color: var(--zrt-text); font-size: 28px; }.login-card-head p { margin: 6px 0 0; color: var(--zrt-muted); }
label { display: grid; gap: 7px; color: var(--zrt-text); font-weight: 500; }
label :deep(.ant-input-prefix) svg { width: 17px; color: var(--zrt-muted); }
.oauth-list { display: flex; flex-wrap: wrap; gap: 8px; }.login-copyright { margin-top: 58px; color: var(--zrt-muted); font-size: 12px; }
@media (max-width: 820px) { .vben-login-page { display: block; background: var(--zrt-bg); }.login-visual { display: none; }.login-panel { background: var(--zrt-bg); }.login-card { padding: 26px; border: 1px solid var(--zrt-border); border-radius: 10px; background: var(--zrt-surface); box-shadow: var(--zrt-shadow); } }
</style>

// web/src/views/LoginView.tsx
import { type FormEvent, useEffect, useMemo, useState } from 'react'
import axios from 'axios'
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom'

import { useAuthStore } from '@/stores/auth'
import { getLoginProviders, type LoginProvider } from '@/api/client'

interface APIError {
  code?: string
  message?: string
  request_id?: string
}

function safeRedirect(value: string | null): string {
  return value?.startsWith('/') && !value.startsWith('//') && !value.includes('\\') ? value : '/'
}

export default function LoginView() {
  const login = useAuthStore((state) => state.login)
  const loginLDAP = useAuthStore((state) => state.loginLDAP)
  const [searchParams] = useSearchParams()
  const location = useLocation()
  const navigate = useNavigate()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  const [providers, setProviders] = useState<LoginProvider[]>([])
  const [credentialProvider, setCredentialProvider] = useState('local')
  const unavailable = searchParams.get('reason') === 'unavailable'
  const ldapProviders = useMemo(() => providers.filter((provider) => provider.type === 'ldap'), [providers])
  const oauthProviders = useMemo(() => providers.filter((provider) => provider.type !== 'ldap'), [providers])

  useEffect(() => {
    void getLoginProviders().then(setProviders).catch(() => setProviders([]))
  }, [])

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!username.trim() || !password) {
      setErrorMessage('请输入用户名和密码。')
      return
    }

    setLoading(true)
    setErrorMessage('')
    try {
      if (credentialProvider === 'local') await login(username, password)
      else await loginLDAP(credentialProvider, username, password)
      navigate(safeRedirect(searchParams.get('redirect')), { replace: true })
    } catch (error) {
      if (axios.isAxiosError<APIError>(error)) {
        setErrorMessage(error.response?.data?.message || '登录服务暂时不可用，请稍后重试。')
      } else {
        setErrorMessage('登录服务暂时不可用，请稍后重试。')
      }
    } finally {
      setLoading(false)
    }
  }

  const externalErrorMessages: Record<string, string> = {
    cancelled: '你取消了外部账号授权。', expired: '登录请求已过期，请重新选择登录方式。',
    not_bound: '这个账号尚未绑定，请联系管理员。', email_unverified: '请先在身份平台验证邮箱。', failed: '外部登录失败，请重试。',
  }
  const externalError = searchParams.get('external_error')
  const returnTo = safeRedirect(searchParams.get('redirect'))

  return (
    <main className="login-page" key={location.key}>
      <section className="login-brand-panel">
        <div className="login-brand">
          <span className="brand-mark large">Z</span>
          <strong>ZRT</strong>
        </div>
        <div className="login-copy">
          <p className="eyebrow">持续交付，从这里开始</p>
          <h1>把代码、构建和发布，<br />清清楚楚地串起来。</h1>
          <p>用一套简单明了的流程，管理应用从代码变更到上线的每一步。</p>
        </div>
        <div className="login-foundation">
          <span>流程清晰</span><span>变更可追踪</span><span>失败可回滚</span>
        </div>
      </section>

      <section className="login-form-panel">
        <form className="login-form" onSubmit={submit}>
          <div>
            <p className="section-label">欢迎回来</p>
            <h2>登录 ZRT</h2>
            <p className="form-description">使用你的 ZRT 账户继续。</p>
          </div>

          {unavailable && (
            <div className="form-alert" role="alert">
              暂时无法读取登录状态，请确认 ZRT API、Redis 与数据库均已启动。
            </div>
          )}
          {errorMessage && <div className="form-alert error" role="alert">{errorMessage}</div>}
          {externalError && <div className="form-alert error" role="alert">{externalErrorMessages[externalError] || externalErrorMessages.failed}</div>}

          {ldapProviders.length > 0 && <div className="credential-tabs" role="tablist" aria-label="账号来源">
            <button className={credentialProvider === 'local' ? 'active' : ''} type="button" onClick={() => setCredentialProvider('local')}>ZRT 账号</button>
            {ldapProviders.map((provider) => <button className={credentialProvider === provider.id ? 'active' : ''} key={provider.id} type="button" onClick={() => setCredentialProvider(provider.id)}>{provider.display_name}</button>)}
          </div>}

          <label>
            <span>用户名</span>
            <input
              value={username}
              onChange={(event) => setUsername(event.target.value)}
              name="username"
              autoComplete="username"
              maxLength={32}
              autoFocus
              placeholder="请输入用户名"
            />
          </label>
          <label>
            <span>密码</span>
            <input
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              name="password"
              type="password"
              autoComplete="current-password"
              maxLength={512}
              placeholder="请输入密码"
            />
          </label>
          <button className="login-button" type="submit" disabled={loading}>
            {loading ? '正在验证…' : '登录控制台'}
          </button>
          {oauthProviders.length > 0 && <div className="external-login">
            <div className="login-divider"><span>或者使用</span></div>
            <div className="external-login-grid">{oauthProviders.map((provider) => (
              <button key={provider.id} type="button" onClick={() => window.location.assign(`/api/v1/auth/oauth/${encodeURIComponent(provider.id)}/start?return_to=${encodeURIComponent(returnTo)}`)}>
                <span className={`provider-logo ${provider.type}`}>{provider.type === 'generic_oauth' ? 'O' : provider.display_name.slice(0, 1)}</span>{provider.display_name}
              </button>
            ))}</div>
          </div>}
        </form>
        <p className="login-footer">ZRT · 让交付更简单</p>
      </section>
    </main>
  )
}
